import "./home.css";
import { createButton } from "../button/button";
export function pintarHTML() {
  let appInfo = document.querySelector('#app');
  //Crear el Header
  const headerHTML = document.createElement("header");
  const divHeaderContainer = document.createElement("div");
  const imgIconePinterest = document.createElement("img");
  const headerSearchContainer = document.createElement("div");
  const spanIcon = document.createElement("span");
  const inputInfo = document.createElement("input");
  const imgDesktopIconCampana = document.createElement("img");
  const imgDesktopIconComments = document.createElement("img");
  divHeaderContainer.className = "headerContainer";
  imgIconePinterest.className = "iconePinterest";
  imgIconePinterest.src = "./assets/pinterest_logo.png";
  headerSearchContainer.className = "headerSearchContainer";
  spanIcon.className = "icon";
  spanIcon.innerHTML = "🔍";
  inputInfo.className = "inputInfo";
  inputInfo.id = "word";
  inputInfo.type = "text";
  inputInfo.placeholder = "Buscar...";
  imgDesktopIconCampana.className = "desktopIconCampana";
  imgDesktopIconCampana.src = "./assets/campana.png";
  imgDesktopIconComments.className = "desktopIconComments";
  imgDesktopIconComments.src = "./assets/comentarios.png";
  appInfo.appendChild(headerHTML);
  headerHTML.appendChild(divHeaderContainer);
  divHeaderContainer.appendChild(imgIconePinterest);
  divHeaderContainer.innerHTML += createButton({ classInfo: "initButton", texto: "Inicio" });
  divHeaderContainer.innerHTML += createButton({ classInfo: "initButton", texto: "Explorar" });
  divHeaderContainer.innerHTML += createButton({ classInfo: "initButton", texto: "Crear" });
  divHeaderContainer.appendChild(headerSearchContainer);
  headerSearchContainer.appendChild(spanIcon);
  headerSearchContainer.appendChild(inputInfo);
  divHeaderContainer.appendChild(imgDesktopIconCampana);
  divHeaderContainer.appendChild(imgDesktopIconComments);
  divHeaderContainer.innerHTML += createButton({ classInfo: "upRightButton", bgColor: "var(--rtc-color-fondo-1)", texto: "D" });
  //Crear el Main
  const mainHTML = document.createElement("main");
  const divNotification = document.createElement("div");
  const notificationH2 = document.createElement("h2");
  const divContainerCards = document.createElement("div");
  divNotification.id = "notification";
  notificationH2.className = "notificationH2";
  notificationH2.innerHTML = `¡Busqueda errónea!, por favor inténtalo con palabras como gato, perro...`;
  divContainerCards.id = "containerCards";
  appInfo.appendChild(mainHTML);
  mainHTML.appendChild(divNotification);
  divNotification.appendChild(notificationH2);
  divNotification.innerHTML += createButton({ classInfo: `tryAgain`, bgColor: "var(--rtc-bgColor2)", texto: "¡Pulsa para intentarlo de nuevo!" });
  mainHTML.appendChild(divContainerCards);
};